### ISSUE TITLE
HAProxy supervisord

### ISSUE THREAD

**Issue by jone** [4teamwork/gever-buildouts#23]
Das HaProxy-Supervisor-Plugin ist bei GEVER im Moment nicht im Einsatz.
Dies kann zu Proxy Errors während Betrieb und während Updates führen.
Meines Wissens wird mittlerweile auf Stufe Apache / HaProxy nichts abgehängt während eines Updates.

Das Plugin wurde mit #18 weil bei St. Gallen und Zug der HaProxy auf einem anderen Host ist.
Der Host kann im Buildout mit `buildout:supervisor-haproxy-socket` geändert werden; entsprechende Firewall-Regel ist nötig.
Alternativ kann durch überschreiben von `supervisor:eventlisteners` das Plugin komplett deaktiviert werden.

Allenfalls muss `ftw.maintenanceserver` noch robuster gemacht werden (connection timeouts).

Ich finde wir sollten grundsätzlich bei GEVER das Plugin einsetzen. Wenn es bei St. Gallen und Zug nicht funktioniert heisst das noch nicht dass wir es sonst nirgends einsetzen sollen.

Ideen und Meinungen?

/cc @4teamwork/gever @mhubi

**Comment by lukasgraf** [comment]
@jone 
> Ich finde wir sollten grundsätzlich bei GEVER das Plugin einsetzen. Wenn es bei St. Gallen und Zug nicht funktioniert heisst das noch nicht dass wir es sonst nirgends einsetzen sollen.

Sehe ich grundsätzlich auch so. In Fällen wie St. Gallen und Zug, wo der Control-Socket auch von aussen erreichbar ist, muss Zugriff auf diesen aber zuverlässig geschützt werden.
